version: '3.8'
services:
  kvs-server:
    container_name: kvs-server
    build:
      context: .
      dockerfile: Dockerfile.kvs-server
    environment:
      LISTEN_PORT: ":8080"

  gateway-server:
    container_name: gateway-server
    build:
      context: .
      dockerfile: Dockerfile.gateway-server
    environment:
      LISTEN_PORT: ":8081"
      GRPC_SERVER_ADDRESS: "kvs-server:8080"
    ports:
      - "8081:8081"
    depends_on:
      - kvs-server



